language: c
dist: bionic
install:
    - apt search aarch64
    - sudo apt-get install -y gcc-aarch64-linux-gnu tree
    - ls /usr/bin/aarch64*
    - cd /tmp
    - wget https://developer.download.nvidia.com/embedded/L4T/r32_Release_v1.0/jetson-nano/BSP/Jetson-Nano-Tegra210_Linux_R32.1.0_aarch64.tbz2
    - tar -xvjf Jetson-Nano-Tegra210_Linux_R32.1.0_aarch64.tbz2
    - ls /tmp
script:
  - echo Hello World
  - cd /tmp/Linux_for_Tegra
  - ./source_sync.sh -t tegra-l4t-r32.3.1
  - export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-
  - export LOCALVERSION=-tegra
  - echo $LOCALVERSION
  - cd sources/kernel/kernel-4.9
  - mkdir /tmp/kernel
  - mkdir /tmp/modules
  - make ARCH=arm64 O=/tmp/kernel tegra_defconfig
  - make ARCH=arm64 O=/tmp/kernel -j$(nproc --all)
  - make ARCH=arm64 O=/tmp/modules modules_install
  - tree /tmp/kernel
  - tree /tmp/modules
