language: c
dist: bionic
install:
    - apt search aarch64
    - sudo apt-get install -y gcc-7-aarch64-linux-gnu
    - cd /tmp
    - wget https://developer.download.nvidia.com/embedded/L4T/r32_Release_v1.0/jetson-nano/BSP/Jetson-Nano-Tegra210_Linux_R32.1.0_aarch64.tbz2
    - tar -xvjf Jetson-Nano-Tegra210_Linux_R32.1.0_aarch64.tbz2
    - ls /tmp
script:
  - echo Hello World
  - cd /tmp/Linux_for_Tegra
  - ./source_sync.sh -t tegra-l4t-r32.3.1
  - export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-gcc-7
  - ls /usr/bin/aarch64
  - export LOCALVERSION=-tegra
  - echo $LOCALVERSION
  - cd sources/kernel/kernel-4.9
  - make ARCH=arm64 O=/tmp tegra_defconfig
  - make ARCH=arm64 O=/tmp -j4
